
/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  "aws_project_region": "ap-south-1",
  "aws_cognito_identity_pool_id": "ap-south-1:d1d9188d-8a65-4d13-bd76-fd51362d9945",
  "aws_cognito_region": "ap-south-1",
  "aws_user_pools_id": "ap-south-1_ioH3suKuB",
  "aws_user_pools_web_client_id": "46v6320al98ehi9vup9p39u0an",
  "oauth": {},
  "aws_cognito_username_attributes": [],
  "aws_cognito_social_providers": [],
  "aws_cognito_signup_attributes": [
      "EMAIL"
  ],
  "aws_cognito_mfa_configuration": "OFF",
  "aws_cognito_mfa_types": [
      "SMS"
  ],
  "aws_cognito_password_protection_settings": {
      "passwordPolicyMinLength": 8,
      "passwordPolicyCharacters": []
  },
  "aws_cognito_verification_mechanisms": [
      "EMAIL"
  ],
  "aws_appsync_graphqlEndpoint":"https://ydimmbeekrgqxeiqispoynndf4.appsync-api.ap-south-1.amazonaws.com/graphql",
  "aws_appsync_region": "ap-south-1",
  "aws_appsync_authenticationType": "API_KEY",
  "aws_appsync_apiKey": "da2-pc5thf27hvbjbi6hpzglvs5jyq"
};


export default awsmobile;
